In [60]:
import numpy as np
import pandas as pd

In [61]:
n = 3+16+15
order = "deglex" # block-monomial order
R.< \
    a21, a41, a43, \
    ge11, ge12, ge13, ge14, ge21, ge22, ge23, ge24, ge31, ge32, ge33, ge34, ge41, ge42, ge43, ge44,\
    gf11, gf12, gf13, gf21, gf22, gf23, gf31, gf32, gf33, gf41, gf42, gf43, gf51, gf52, gf53 \
> = PolynomialRing(QQ, n, order=order)
R.inject_variables()

Defining a21, a41, a43, ge11, ge12, ge13, ge14, ge21, ge22, ge23, ge24, ge31, ge32, ge33, ge34, ge41, ge42, ge43, ge44, gf11, gf12, gf13, gf21, gf22, gf23, gf31, gf32, gf33, gf41, gf42, gf43, gf51, gf52, gf53


In [62]:
A = matrix([[0, 0, 0, 0, 0],
            [a21, 0, 0, 0, 0], 
            [0, 0, 0, 0, 0], 
            [a41, 0, a43, 0, 0], 
            [0, 0, 0, 0, 0]])
A

[  0   0   0   0   0]
[a21   0   0   0   0]
[  0   0   0   0   0]
[a41   0 a43   0   0]
[  0   0   0   0   0]

In [63]:
G_e = matrix([[ge11, ge12, ge13, 0], 
              [ge21, 0, ge23, 0], 
              [0, ge32, ge33, ge34], 
              [ge41, ge42, ge43, ge44]])
G_e

[ge11 ge12 ge13    0]
[ge21    0 ge23    0]
[   0 ge32 ge33 ge34]
[ge41 ge42 ge43 ge44]

In [71]:
G_f = matrix([[gf11, 0, gf13],
              [gf21, gf22, gf23],
              [0, gf32, 0],
              [gf41, gf42, gf43],
              [gf51, gf52, 0]])
G_f

[gf11    0 gf13]
[gf21 gf22 gf23]
[   0 gf32    0]
[gf41 gf42 gf43]
[gf51 gf52    0]

In [72]:
Id = identity_matrix(5)
Id

[1 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 0 0 1]

In [73]:
(Id - A).inverse()

[  1   0   0   0   0]
[a21   1   0   0   0]
[  0   0   1   0   0]
[a41   0 a43   1   0]
[  0   0   0   0   1]

In [74]:
G = matrix(R, 9,5)

# Shared columns
G[:4,[0,1]] = G_e[:,[0,1]]
G[4:,[0,1]] = G_f[:,[0,1]]

# Domain-specific columns
G[:4,[2,3]] = G_e[:,[2,3]]
G[4:,4] = G_f[:,2]

G

[ge11 ge12 ge13    0    0]
[ge21    0 ge23    0    0]
[   0 ge32 ge33 ge34    0]
[ge41 ge42 ge43 ge44    0]
[gf11    0    0    0 gf13]
[gf21 gf22    0    0 gf23]
[   0 gf32    0    0    0]
[gf41 gf42    0    0 gf43]
[gf51 gf52    0    0    0]

In [75]:
B = G * (Id - A).inverse()

In [76]:
%display latex
B

[           a21*ge12 + ge11                       ge12                       ge13                          0                          0]
[                      ge21                          0                       ge23                          0                          0]
[       a21*ge32 + a41*ge34                       ge32            a43*ge34 + ge33                       ge34                          0]
[a21*ge42 + a41*ge44 + ge41                       ge42            a43*ge44 + ge43                       ge44                          0]
[                      gf11                          0                          0                          0                       gf13]
[           a21*gf22 + gf21                       gf22                          0                          0                       gf23]
[                  a21*gf32                       gf32                          0                          0                          0]
[           a21*gf42 + gf41                       gf42                          0                          0                       gf43]
[           a21*gf52 + gf51                       gf52                          0                          0                          0]